--- #YAML:1.0
name:               Net-SSH-Perl-ProxiedIPC
version:            0.01
abstract:           ~
author:
    - Jennie Rose Evers-Corvina <seven@nanabox.net>
license:            unknown
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    Carp:            0
    IPC::PerlSSH:    0
    Net::SSH::Perl:  0
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.56
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
